{
 "title": "DWD Phenological Data",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "states",
    "label": "Filter by state",
    "query": "select distinct state from dwd_stations"
   }
  ]
 },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard renders phenological data from [DWD](https://www.dwd.de).\nPhenological phases are grouped into five categories by assigning a numeric weight to each phase depending on the progress it represents (see legend below).\nPlants are divided into three categories:\n**_crops_** (wheat, oat, potato, etc),\n**_fruit plants_** (cherry, apples, berries, etc) and\n**_wild_** (birch, hazel, etc).\nIn order to narrow the results you can filter by state."
   },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 2 },
   "options": { "content": "![](/data/legend.png)" },
   "content": "![](http://164.90.181.109/legend.png)",
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Crops",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 4 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  weight AS metric,\n  lon,\n  lat,\n  station AS \"title\"\nFROM dwd_records_cache_crops\nWHERE\n  $__timeFilter(date) AND\n  state IN($states)\nORDER BY date"
    }
   ]
  },
  {
   "title": "Fruits",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 4 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  weight AS metric,\n  lon,\n  lat,\n  station AS \"title\"\nFROM dwd_records_cache_fruits\nWHERE\n  $__timeFilter(date) AND\n  state IN($states)\nORDER BY date"
    }
   ]
  },
  {
   "title": "Wild",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 4 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  weight AS metric,\n  lon,\n  lat,\n  station AS \"title\"\nFROM dwd_records_cache_wild\nWHERE\n  $__timeFilter(date) AND\n  state IN($states)\nORDER BY date"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "DWD phase decoding",
   "type": "text",
   "gridPos": { "h": 30, "w": 7, "x": 0, "y": 20 },
   "options": {
    "content": "| Color                 | Name                                     |\n|:---------------------:|------------------------------------------|\n| ![](/data/blue.png)   | first cut for hay                        |\n| ![](/data/blue.png)   | autumn needle fall                       |\n| ![](/data/blue.png)   | autumn colouring of needles              |\n| ![](/data/blue.png)   | autumn leave fall                        |\n| ![](/data/blue.png)   | autumn colouring of leaves               |\n| ![](/data/blue.png)   | second cut for silage                    |\n| ![](/data/blue.png)   | second cut for hay                       |\n| ![](/data/blue.png)   | first cut for silage                     |\n| ![](/data/green.png)  | beginning of turning green               |\n| ![](/data/green.png)  | beginning of may sprouting               |\n| ![](/data/green.png)  | beginning of unfoalding of leaves        |\n| ![](/data/green.png)  | first bleeding of the vines              |\n| ![](/data/green.png)  | sprouting of leaves                      |\n| ![](/data/yellow.png) | general flowering                        |\n| ![](/data/yellow.png) | beginning of emergence                   |\n| ![](/data/yellow.png) | beginning of tilling sowing drilling     |\n| ![](/data/yellow.png) | beginning of flowering                   |\n| ![](/data/orange.png) | tip of tassel visible                    |\n| ![](/data/orange.png) | end of flowering in the observation area |\n| ![](/data/orange.png) | beginning tassel emergence               |\n| ![](/data/orange.png) | beginning of growth in height            |\n| ![](/data/orange.png) | end of flowering                         |\n| ![](/data/orange.png) | yellow ripeness                          |\n| ![](/data/orange.png) | beginning of heading                     |\n| ![](/data/purple.png) | fruit ripe for picking                   |\n| ![](/data/purple.png) | harvest                                  |\n| ![](/data/purple.png) | grape harvest                            |"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  }
 ]
}